# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cardDescrition',
            field=models.CharField(max_length=64, null=True, verbose_name='卡片描述'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='detailDescription',
            field=models.CharField(max_length=128, null=True, verbose_name='交易描述'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='tradeNumber',
            field=models.BigIntegerField(verbose_name='交易编号'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='installmentDescription',
            field=models.CharField(max_length=128, null=True, verbose_name='贷款描述'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectDescrition',
            field=models.CharField(max_length=128, null=True, verbose_name='科目描述'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='tradeDescrition',
            field=models.CharField(max_length=64, null=True, verbose_name='账目说明'),
        ),
        migrations.AlterField(
            model_name='user',
            name='familyMarkName',
            field=models.CharField(max_length=64, null=True, verbose_name='用户在家庭的简称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.Family', verbose_name='用户的家庭'),
        ),
    ]
